name: Deploy .NET 9 App to Azure App Service

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore ./src/eshop-microservices.csproj

    - name: Build
      run: dotnet build ./src/eshop-microservices.csproj --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ./src/eshop-microservices.csproj --configuration Release --output ./publish

    - name: Azure Login (Client Credentials)
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: "eshop-microservices-webapp-dev"
        package: "./publish"
